# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanagers configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
          #

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - /etc/prometheus/rules/prometheus.rules
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
    - job_name: "prm0"
      static_configs:
        - targets: ["localhost:9090"]

    - job_name: 'apache'
      static_configs:
        - targets: ['192.168.122.111:80']
        - targets: ['192.168.122.11:80']

    - job_name: 'web_0'
      static_configs:
        - targets: ['192.168.122.111:9100']  # Replace with the exporter's IP and port      

    - job_name: 'web_1'
      static_configs:
        - targets: ['192.168.122.11:9100']

    - job_name: 'lb0'
      static_configs:
        - targets: ['192.168.122.230:9100']

    - job_name: 'gitlab'
      static_configs:
        - targets: ['192.168.122.148:443']

    - job_name: 'salt_master'
      static_configs:
        - targets: ['192.168.122.35:9100']

    - job_name: 'haproxy'
      static_configs:
        - targets: ['192.168.122.230:8404']

    - job_name: 'prometheus'
      static_configs:
        - targets: ['192.168.122.228:9090']
        #- targets: ['192.168.122.228:9100']  
